# Generated by Django 5.1.2 on 2024-11-06 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(null=True)),
                ('template', models.TextField()),
                ('version', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_report', models.JSONField(blank=True)),
                ('start_time', models.DateTimeField(blank=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('output', models.JSONField(blank=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='backend.pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineRunJobReport',
            fields=[
                ('name', models.SlugField(primary_key=True, serialize=False)),
                ('output', models.TextField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='backend.pipelinerun')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('workflow_step', models.TextField()),
                ('definition', models.TextField()),
                ('is_cwl', models.BooleanField()),
                ('version', models.CharField(max_length=50, null=True)),
                ('tags', models.ManyToManyField(related_name='tools', to='backend.tag')),
                ('tools', models.ManyToManyField(blank=True, to='backend.tool')),
            ],
        ),
        migrations.AddField(
            model_name='pipeline',
            name='tools',
            field=models.ManyToManyField(to='backend.tool'),
        ),
    ]
