# Generated by Django 5.1.2 on 2024-11-07 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('output', models.TextField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobreports', to='backend.pipelinerun')),
            ],
        ),
        migrations.DeleteModel(
            name='PipelineRunJobReport',
        ),
    ]
