# Generated by Django 4.2.16 on 2024-10-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pipelinerunjobreport',
            name='content',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='slug',
            field=models.SlugField(default='', primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipelinerunjobreport',
            name='output',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='definition',
            field=models.JSONField(),
        ),
    ]
