# Generated by Django 4.2.16 on 2024-10-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_pipeline_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinerun',
            name='cwl',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pipelinerunjobreport',
            name='name',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('definition', models.JSONField()),
                ('tags', models.TextField(choices=[('py', 'Python'), ('js', 'JavaScript'), ('cpp', 'C++')])),
                ('is_cwl', models.BooleanField()),
                ('version', models.CharField(max_length=50)),
                ('tools', models.ManyToManyField(to='backend.tool')),
            ],
        ),
        migrations.AddField(
            model_name='pipeline',
            name='tools',
            field=models.ManyToManyField(to='backend.tool'),
        ),
    ]
