# Generated by Django 5.1.2 on 2024-11-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_jobreport_delete_pipelinerunjobreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='executed_cwl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelinerun',
            name='inputs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='output',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
