# Generated by Django 5.1.4 on 2025-03-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_pipeline_created_at_pipeline_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='default_inputs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
