# Generated by Django 5.1.2 on 2024-11-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_pipelinerun_executed_cwl_pipelinerun_inputs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobreport',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
