# Generated by Django 4.2.16 on 2024-10-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_pipelinerun_cwl_pipeline_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='version',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
