# Generated by Django 4.2.16 on 2024-10-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_pipeline_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tool',
            name='tags',
        ),
        migrations.AddField(
            model_name='tool',
            name='tags',
            field=models.ManyToManyField(related_name='tools', to='backend.tag'),
        ),
    ]
