# Generated by Django 5.1.8 on 2025-11-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_create_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobreport',
            name='instance',
            field=models.CharField(default='', max_length=200),
        ),
    ]