# Generated by Django 4.2.16 on 2024-10-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_tag_remove_tool_tags_tool_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tools',
            field=models.ManyToManyField(null=True, to='backend.tool'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='version',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
