# Generated by Django 5.1.2 on 2024-11-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_tool_workflow_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='workflow_step',
            field=models.TextField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
