# Generated by Django 5.1.8 on 2025-12-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_jobreport_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='subworkflow',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subworkflow',
            name='status',
            field=models.CharField(choices=[('Beta', 'Beta'), ('Candidate', 'Candidate'), ('Disabled', 'Disabled'), ('Stable', 'Stable'), ('Deprecated', 'Deprecated')], default='Stable', max_length=20),
        ),
    ]
