# Generated by Django 4.2.16 on 2024-10-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_tool_tools_alter_tool_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tools',
            field=models.ManyToManyField(blank=True, to='backend.tool'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
