# Generated by Django 5.1.3 on 2024-11-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_tool_workflow_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLineTool',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('definition', models.TextField()),
                ('version', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subworkflow',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('pipeline_step', models.TextField(blank=True)),
                ('definition', models.TextField()),
                ('version', models.CharField(max_length=50)),
                ('tags', models.ManyToManyField(blank=True, related_name='subworkflows', to='backend.tag')),
                ('tools', models.ManyToManyField(related_name='subworkflows', to='backend.commandlinetool')),
            ],
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='tools',
            field=models.ManyToManyField(blank=True, to='backend.subworkflow'),
        ),
    ]
