# Generated by Django 5.1.8 on 2026-03-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_tool_subworkflow_status_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerType',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('event_type_prefix', models.CharField(max_length=100)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('Disabled', 'Disabled'), ('Testing', 'Testing'), ('Restricted', 'Restricted'), ('Enabled', 'Enabled'), ('Deleted', 'Deleted')], default='Enabled', max_length=20)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trigger Type',
                'verbose_name_plural': 'Trigger Types',
            },
        ),
    ]
