# Generated by Django 5.1.8 on 2026-03-18 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_triggertype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('cql2_filter', models.JSONField(blank=True, default=dict, help_text='Filter expressed in CQL2-JSON', verbose_name='CQL2-JSON filter')),
                ('params_default', models.JSONField(blank=True, default=dict)),
                ('params_mapping', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('Disabled', 'Disabled'), ('Testing', 'Testing'), ('Restricted', 'Restricted'), ('Enabled', 'Enabled'), ('Deleted', 'Deleted')], default='Enabled', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='backend.pipeline')),
                ('trigger_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='backend.triggertype')),
            ],
        ),
        migrations.CreateModel(
            name='TriggerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('event_time', models.DateTimeField()),
                ('event_type', models.CharField(max_length=100)),
                ('event_headers', models.JSONField(blank=True, default=dict)),
                ('event_body', models.JSONField(blank=True, default=dict)),
                ('pipeline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_by', to='backend.pipelinerun')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_events', to='backend.trigger')),
            ],
        ),
    ]