# Generated by Django 5.1.3 on 2024-11-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_commandlinetool_subworkflow_alter_pipeline_tools_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subworkflow',
            name='pipeline_step',
            field=models.TextField(),
        ),
    ]
