# Generated by Django 4.2.16 on 2024-10-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_tool_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerun',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='output',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='usage_report',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='user',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
    