# Generated by Django 5.1.8 on 2026-07-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_trigger_triggerevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='digest',
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobreport',
            name='digest',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]