# Generated by Django 5.1.3 on 2024-11-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_subworkflow_pipeline_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobreport',
            name='output',
            field=models.JSONField(),
        ),
    ]
