# Generated by Django 5.1.8 on 2026-07-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_pipelinerun_and_jobreport_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='quality_rules',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
