# Generated by Django 4.2.16 on 2024-10-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_pipelinerun_completion_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
    