# Generated by Django 4.2.16 on 2024-10-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_pipelinerun_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerun',
            name='user',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
