# Generated by Django 4.2.16 on 2024-10-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_pipelinerun_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerun',
            name='output',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pipelinerun',
            name='usage_report',
            field=models.JSONField(blank=True),
        ),
    ]
