# Generated by Django 5.1.4 on 2025-02-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_pipelinerun_started_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='subworkflow',
            name='user_params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
