# Generated by Django 5.1.2 on 2024-10-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_pipelinerun_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tools', to='backend.tag'),
        ),
    ]
