# Generated by Django 5.1.2 on 2024-11-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_tool_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='workflow_step',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tool',
            name='tags',
            field=models.ManyToManyField(related_name='tools', to='backend.tag'),
        ),
    ]
