# Generated by Django 5.1.4 on 2025-02-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_subworkflow_user_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subworkflow',
            name='user_params',
            field=models.JSONField(default=dict),
        ),
    ]
