# Generated by Django 5.1.2 on 2024-11-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_tool_workflow_step_alter_tool_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='definition',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='template',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
