# Generated by Django 5.1.2 on 2024-11-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_remove_pipeline_definition_pipeline_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='definition',
            field=models.TextField(),
        ),
    ]
