apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application-quality.fullname" . }}-api
  labels:
    app.kubernetes.io/component: "api"
    {{- include "application-quality.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: "api"
      {{- include "application-quality.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: "api"
        {{- include "application-quality.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.api.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "application-quality.fullname" . }}-serviceaccount
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.containerPort }}
          command:
            - supervisord
            - -c
            - /etc/supervisor/supervisord.conf
          envFrom:
            - configMapRef:
                name: {{ include "application-quality.fullname" . }}-api-env
            #- secretRef:
            #    name: application-quality-db-creds
            - secretRef:
                name: application-quality-auth-client
            {{- if .Values.grafana.enabled }}
            - secretRef:
                name: application-quality-grafana-dashboards-admin-creds
            {{- end }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}