apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-quality.fullname" . }}-api
  labels:
    app.kubernetes.io/component: "api"
    {{- include "application-quality.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.serviceType }}
  ports:
    - port: {{ .Values.api.servicePort }}
      targetPort: {{ .Values.api.containerPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: "api"
    {{- include "application-quality.selectorLabels" . | nindent 4 }}