apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application-quality.fullname" . }}-api-env
data:
  PUBLIC_URL: {{ .Values.web.publicUrl }}

  {{- if .Values.vclusters.enabled }}
  BACKEND_SERVICE_HOST: backend-service.default.svc.local.cluster
  {{- else }}
  BACKEND_SERVICE_HOST: {{ include "application-quality.fullname" . }}-api.{{ .Release.Namespace }}.svc.cluster.local
  {{- end }}
  BACKEND_SERVICE_PORT: {{ .Values.api.containerPort | quote }}

  BACKEND_SERVICE_ADMIN_USER: {{ .Values.api.adminUser | quote }}
  BACKEND_SERVICE_ADMIN_PASSWORD: {{ .Values.api.adminPassword | quote }}
  BACKEND_SERVICE_ADMIN_EMAIL: {{ .Values.api.adminEmail | quote }}
  
  # Database
  DB_NAME: {{ .Values.db.name }}
  DB_HOST: {{ include "application-quality.fullname" . }}-db
  DB_PORT: {{ .Values.db.containerPort | quote }}
  # TODO: From secret
  DB_USER: {{ .Values.db.user }}
  DB_PASSWORD: {{ .Values.db.password | quote }}

  # Grafana
  GRAFANA_ENABLED: {{ .Values.grafana.enabled | default false | quote }}

  # TBD
  AQBB_STORAGECLASS: {{ .Values.calrissian.storageClassName }}
  AQBB_VOLUMESIZE: {{ .Values.calrissian.volumeSize | quote }}
  AQBB_CALRISSIANIMAGE: {{ .Values.calrissian.image }}
  AQBB_MAXCORES: {{ .Values.calrissian.maxCores | quote }}
  AQBB_MAXRAM: {{ .Values.calrissian.maxRam | quote }}

  OIDC_ENABLED: {{ .Values.oidc.enabled | default false | quote }}
  {{- if .Values.oidc.enabled }}
  # From Sealed Secret: OIDC_RP_CLIENT_ID: {{ .Values.oidc.clientId }}
  # From Sealed Secret: OIDC_RP_CLIENT_SECRET: {{ .Values.oidc.clientSecret }}
  OIDC_CONNECT_CONFIG_URL: {{ .Values.oidc.realmBaseUrl }}/.well-known/openid-configuration
  LOGIN_URL: {{ .Values.oidc.loginUrl }}
  LOGIN_REDIRECT_URL: {{ .Values.oidc.loginRedirectUrl }}
  LOGOUT_REDIRECT_URL: {{ .Values.oidc.logoutRedirectUrl }}
  OIDC_RP_REDIRECT_URI: {{ .Values.oidc.rpRedirectUri }}
  OIDC_RP_SIGN_ALGO: {{ .Values.oidc.rpSignAlgo }}
  OIDC_LOGOUT_ENDPOINT_PATH: {{ .Values.oidc.logoutEndpointPath }}
  OIDC_LOGOUT_REDIRECT_URI_PARAMETER_NAME: {{ .Values.oidc.logoutRedirectUrlParameterName }}
  OIDC_POST_LOGOUT_REDIRECT_URL: {{ .Values.oidc.postLogoutRedirectUrl }}
  # TODO: The following values must be obtained from the OpenID configuration
  OIDC_OP_AUTHORIZATION_ENDPOINT: {{ .Values.oidc.realmBaseUrl }}/protocol/openid-connect/auth
  OIDC_OP_TOKEN_ENDPOINT: {{ .Values.oidc.realmBaseUrl }}/protocol/openid-connect/token
  OIDC_OP_USER_ENDPOINT: {{ .Values.oidc.realmBaseUrl }}/protocol/openid-connect/userinfo
  OIDC_OP_JWKS_ENDPOINT: {{ .Values.oidc.realmBaseUrl }}/protocol/openid-connect/certs
  {{- end }}
  {{- if .Values.sonarqube.enabled }}
  SONARQUBE_SERVER: {{ .Values.sonarqube.serverUrl }}
  SONARQUBE_TOKEN: {{ .Values.sonarqube.accessToken }}
  {{- end }}
  # vCluster
  SHARED_VCLUSTER_ENABLED: {{ .Values.vclusters.enabled | default false | quote }}
  {{- if .Values.vclusters.enabled }}
  SHARED_VCLUSTER_REQUIRED: {{ .Values.vclusters.required | default false | quote }}
  SHARED_VCLUSTER_NAME: {{ tpl .Values.vclusters.name . }}
  SHARED_VCLUSTER_NAMESPACE: {{ tpl .Values.vclusters.namespace . }}
  SHARED_VCLUSTER_SERVICE: {{ .Values.vclusters.backend_service | default "default/backend-service" }}
  HOST_CLUSTER_SERVICE: {{ .Release.Namespace }}/{{ include "application-quality.fullname" . }}-api
  KUBECONFIG: /root/.kube/config
  {{- end }}
  # Workspace vClusters
  WORKSPACE_VCLUSTER_ENABLED: {{ .Values.workspace.vcluster.enabled | default false | quote }}
  {{- if .Values.workspace.vcluster.enabled }}
  WORKSPACE_VCLUSTER_REQUIRED: {{ .Values.workspace.vcluster.required | default false | quote }}
  WORKSPACE_API_SERVICE_URL: {{ .Values.workspace.apiServiceUrl | default "" }}
  {{- end }}