apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application-quality.fullname" . }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "application-quality.fullname" . }}-db
  template:
    metadata:
      labels:
        app: {{ include "application-quality.fullname" . }}-db
    spec:
      containers:
        - name: db
          image: {{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.db.containerPort }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.name }}
            - name: POSTGRES_USER
              value: {{ .Values.db.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password | quote }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: {{ include "application-quality.fullname" . }}-db-data