apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "application-quality.fullname" . }}-db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.storage.size }}
  storageClassName: {{ .Values.persistence.storageClassName }}