apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-quality.fullname" . }}-db
spec:
  ports:
    - port: {{ .Values.db.servicePort }}
  selector:
    app: {{ include "application-quality.fullname" . }}-db
  clusterIP: None