{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "application-quality.fullname" . }}
  labels:
    {{- include "application-quality.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.domain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "application-quality.fullname" . }}-web
                port:
                  number: {{ .Values.web.servicePort }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "application-quality.fullname" . }}-api
                port:
                  number: {{ .Values.api.servicePort }}
          - path: /oidc
            pathType: Prefix
            backend:
              service:
                name: {{ include "application-quality.fullname" . }}-api
                port:
                  number: {{ .Values.api.servicePort }}
          - path: /static
            pathType: Prefix
            backend:
              service:
                name: {{ include "application-quality.fullname" . }}-api
                port:
                  number: {{ .Values.api.servicePort }}
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: {{ include "application-quality.fullname" . }}-api
                port:
                  number: {{ .Values.api.servicePort }}
{{- end }}