{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "application-quality.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "application-quality.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessMode | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClassName }}
  {{- if (eq "-" .Values.persistence.storageClassName) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  {{- end }}
{{- end -}}
