apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "application-quality.fullname" . }}:vcluster-manager-role
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets", "deployments"]
  verbs: ["get", "list", "create", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "create"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["delete", "patch", "update"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["delete", "patch", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["update"]
- apiGroups: [""]
  resources: ["pods/attach"]
  verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/ephemeralcontainers"]
  verbs: ["patch", "update"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "delete", "patch", "update", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["patch", "update"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["delete", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "delete", "patch", "update", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "application-quality.fullname" . }}:vcluster-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "application-quality.fullname" . }}:vcluster-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "application-quality.fullname" . }}-serviceaccount
  namespace: {{ .Release.Namespace }}