apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application-quality.fullname" . }}-web
  labels:
    app.kubernetes.io/component: "web"
    {{- include "application-quality.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: "web"
      {{- include "application-quality.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: "web"
        {{- include "application-quality.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.web.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "application-quality.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: web
          image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.web.containerPort }}
          env:
            - name: VITE_API_PORT
              value: {{ .Values.web.containerPort | quote }}
            - name: BACKEND_SERVICE_HOST
              value: {{ include "application-quality.fullname" . }}-api.{{ .Release.Namespace }}.svc.cluster.local
            - name: BACKEND_SERVICE_PORT
              value: {{ .Values.api.containerPort | quote }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}