
global:
  ## The internal cluster (sub)domain for services in this deployment,
  ## typically <namespace>.svc.cluster.local
  internalDomain: "svc.cluster.local"

  ## A certificate issues for the above domain
  defaultInternalIssuerRef:
    kind: ClusterIssuer
    ## INSTRUCTION: Set to name of certificate issuer for the internal cluster domain
    name: eoepca-ca-clusterissuer

  defaultExternalIssuerRef:
    kind: ClusterIssuer
    ## INSTRUCTION: Set to name of certificate issuer for published services
    name: letsencrypt-prod

application-quality:
  # Values for deploying the Application Quality Building Block in the EOEPCA Develop cluster.

  namespace:
    application-quality

  # Application Quality backend
  api:
    image:
      repository: eoepca/eoepca-appquality-backend
      tag: 2.0.0-rc1

  # Application Quality frontend
  web:
    image:
      repository: eoepca/eoepca-appquality-frontend
      tag: 2.0.0-rc1
    publicUrl: "https://application-quality.develop.eoepca.org"

  persistence:
    enabled: true
    storageClassName: managed-nfs-storage-retain
    createStorageClass: false
    accessMode:
    - ReadWriteOnce
    size: 2Gi

  calrissian:
    image: "terradue/calrissian:0.14.0"
    storageClassName: managed-nfs-storage-retain
    volumeSize: "2Gi"
    maxCores: "2"
    maxRam: "2Gi"

  vclusters:
    enabled: false

  grafana:
    enabled: false

  oidc:
    enabled: true
    realmBaseUrl: "https://iam-auth.apx.develop.eoepca.org/realms/eoepca"
    clientId: application-quality-bb
    clientSecret: ""
    postLogoutRedirectUrl: "https://application-quality.develop.eoepca.org/"
    loginRedirectUrl: "https://application-quality.develop.eoepca.org/"
    rpRedirectUri: "https://application-quality.develop.eoepca.org/"

  sonarqube:
    enabled: false
    serverUrl: application-quality-sonarqube-sonarqube.application-quality.svc.cluster.local:9000
    accessToken: ""

  ingress:
    enabled: true
    className: nginx
    domain: application-quality.develop.eoepca.org
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      ingress.kubernetes.io/ssl-redirect: 'true'
      nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    tls:
      - hosts:
        - application-quality.develop.eoepca.org
        secretName: application-quality-tls

  service:
    type: ClusterIP
    port: 80
