# Default values for Application Quality Building Block.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace:
  application-quality

image:
  repository: nexus.spaceapplications.com/repository/docker-asb-public/eoepca/application-quality
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.1"

persistence:
  enabled: true
  storageClassName: managed-nfs-storage
  accessMode:
  - ReadWriteOnce
  size: 1Gi

ingress:
  enabled: true
  className: nginx
  domain: application-quality.develop.eoepca.org
  annotations:                                       
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: 'true'
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  tls:
    - hosts:                                                                          
        - application-quality.develop.eoepca.org
      secretName: application-quality-tls

service:
  type: ClusterIP
  port: 80

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: false
