name: Backend Development

on:
  push:
    branches: ["backend"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Django tests
    runs-on: ubuntu-latest
    env:
      DB_NAME: aqbbtesting
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
      DB_PORT: 5432

    services:
      postgres_main:
        image: postgres:13
        env:
          DB_NAME: ${{ env.DB_NAME }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12, 3.13]
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - run: cat .env.github >> $GITHUB_ENV
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        env:
          DEBUG: "0"
          DJANGO_SECRET_KEY: ${{ env.DJANGO_SECRET_KEY }}
          DB_USERNAME: ${{ env.POSTGRES_USER }}
          DB_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          DB_HOST: ${{ env.POSTGRES_HOST }}
          DB_DATABASE: ${{ env.POSTGRES_DB }}
          DB_PORT: ${{ env.POSTGRES_PORT }}

        run: |
          python manage.py collectstatic
          python manage.py test
